# Generated by Django 5.0.1 on 2024-01-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=255, unique=True)),
                ('products_description', models.CharField(max_length=25)),
                ('slug', models.CharField(max_length=255)),
                ('sale_price', models.FloatField()),
                ('is_perishable', models.BooleanField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='products')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
