print("calculadora de três numeros")
n1 = int(input("digite um numero "))
n2 = int(input("digite um segundo numero "))
n3 = int(input("digite um terceiro numero"))
c = (n1+n2+n3)
print("a soma dos três é: ", c)
